/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/asterism.ts
 * Command: astryx theme build src/theme/asterism.ts --out src/theme/asterism.theme.css
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.4.5
 */

/**
 * asterism theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { asterismTheme } from './asterism';
 *   import './asterism.css';
 */
export const asterismTheme = {
  name: 'asterism',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#5e5ce6, #8b89ff)",
    "--color-on-accent": "light-dark(#ffffff, #11111a)",
    "--color-background-body": "light-dark(#f7f7f8, #0f1013)",
    "--color-background-surface": "light-dark(#ffffff, #15161a)",
    "--color-background-card": "light-dark(#ffffff, #191a1f)",
    "--color-background-popover": "light-dark(#ffffff, #202126)",
    "--color-background-muted": "light-dark(#f0f0f2, #1d1e23)",
    "--color-text-primary": "light-dark(#17171a, #f4f4f5)",
    "--color-text-secondary": "light-dark(#68686f, #9d9da6)",
    "--color-text-disabled": "light-dark(#a6a6ac, #62626a)",
    "--color-border": "light-dark(rgba(23, 23, 26, 0.10), rgba(244, 244, 245, 0.10))",
    "--color-border-emphasized": "light-dark(rgba(23, 23, 26, 0.20), rgba(244, 244, 245, 0.20))",
    "--radius-inner": "5px",
    "--radius-element": "7px",
    "--radius-container": "10px",
    "--font-family-body": "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Segoe UI\", sans-serif",
    "--font-family-heading": "-apple-system, BlinkMacSystemFont, \"SF Pro Display\", \"Segoe UI\", sans-serif",
    "--font-family-code": "ui-monospace, Menlo, Consolas, monospace",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.875rem"
  },
  components: {
    "button": {
      "base": {
        "fontWeight": "520",
        "letterSpacing": "-0.005em"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
