/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: ../../site/src/theme/asterism.ts
 * Command: astryx theme build ../../site/src/theme/asterism.ts --out src/theme/asterism.theme.css
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.4.5
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const asterismTheme: DefinedTheme;
