/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: ../../site/src/theme/asterism.ts
 * Command: astryx theme build ../../site/src/theme/asterism.ts --out src/theme/asterism.theme.css
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.4.5
 */

/**
 * asterism theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { asterismTheme } from './asterism';
 *   import './asterism.css';
 */
export const asterismTheme = {
  name: 'asterism',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#835500, #F0C04D)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #472C00)",
    "--color-neutral": "light-dark(#201B151A, #E8E2D933)",
    "--color-background-surface": "light-dark(#FFFFFF, #14171C)",
    "--color-background-body": "light-dark(#FAFAF9, #0B0D10)",
    "--color-overlay": "light-dark(#201B1566, #1F1B1599)",
    "--color-overlay-hover": "light-dark(#201B150D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#201B151A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#201B150D, #1F1B1580)",
    "--color-text-primary": "light-dark(#101114, #F4F5F6)",
    "--color-text-secondary": "light-dark(#4A5058, #A8AEB6)",
    "--color-text-disabled": "light-dark(#9A8F83, #655D51)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#201B15, #E8E2D9)",
    "--color-icon-secondary": "light-dark(#4E453B, #B3AA9D)",
    "--color-icon-disabled": "light-dark(#9A8F83, #655D51)",
    "--color-background-card": "light-dark(#FFFFFF, #14171C)",
    "--color-background-popover": "light-dark(#FFFFFF, #191D23)",
    "--color-background-inverted": "light-dark(#201B15, #FFFBF3)",
    "--color-border": "light-dark(rgba(16,17,20,0.10), rgba(244,245,246,0.10))",
    "--color-border-emphasized": "light-dark(rgba(16,17,20,0.24), rgba(244,245,246,0.22))",
    "--color-skeleton": "light-dark(#B5A99D, #4D463A)",
    "--color-track": "light-dark(#B5A99D, #4D463A)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.3125rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.25rem",
    "--font-size-xl": "1.5625rem",
    "--font-size-2xl": "1.9375rem",
    "--font-size-3xl": "2.4375rem",
    "--font-size-4xl": "3.0625rem",
    "--font-size-5xl": "3.8125rem",
    "--text-heading-1-size": "clamp(1.5625rem, 3.2vw, 1.9375rem)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.4194",
    "--text-heading-2-size": "clamp(1.25rem, 2.6vw, 1.5625rem)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.24",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "clamp(2.375rem, 6vw, 3.8125rem)",
    "--text-display-1-weight": "var(--font-weight-medium)",
    "--text-display-1-leading": "1.06",
    "--text-display-2-size": "clamp(1.9375rem, 4.6vw, 3.0625rem)",
    "--text-display-2-weight": "var(--font-weight-medium)",
    "--text-display-2-leading": "1.1",
    "--text-display-3-size": "clamp(1.5625rem, 3.6vw, 2.4375rem)",
    "--text-display-3-weight": "var(--font-weight-medium)",
    "--text-display-3-leading": "1.14",
    "--radius-none": "0px",
    "--radius-inner": "6px",
    "--radius-element": "12px",
    "--radius-container": "18px",
    "--radius-page": "42px",
    "--radius-chat": "42px",
    "--radius-full": "9999px",
    "--duration-fast-min": "130ms",
    "--duration-fast": "160ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "255ms",
    "--duration-medium": "320ms",
    "--duration-medium-max": "400ms",
    "--font-family-body": "system-ui, ui-sans-serif, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "--font-family-heading": "system-ui, ui-sans-serif, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "--font-family-code": "ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace",
    "--asterism-glow": "light-dark(rgba(138,91,0,0.10), rgba(242,193,78,0.16))",
    "--asterism-glow-wide": "light-dark(rgba(138,91,0,0.03), rgba(242,193,78,0.055))",
    "--asterism-accent-soft": "light-dark(rgba(138,91,0,0.09), rgba(242,193,78,0.13))",
    "--asterism-edge": "light-dark(rgba(16,17,20,0.04), rgba(244,245,246,0.10))",
    "--asterism-term-bg": "#08090B",
    "--asterism-term-chrome": "#14171C",
    "--asterism-term-fg": "#F4F5F6",
    "--asterism-term-dim": "rgba(244,245,246,0.62)",
    "--asterism-term-line": "rgba(244,245,246,0.10)",
    "--asterism-term-ok": "#7FD1A6",
    "--asterism-term-accent": "#F2C14E"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "base": {
        "letterSpacing": "-0.025em"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "fontWeight": "550",
        "letterSpacing": "-0.01em"
      }
    },
    "link": {
      "base": {
        "textUnderlineOffset": "0.2em"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
