#!/bin/sh
# Publish this instance's environment to login shells.
#
# `ast attach` arrives over ssh, and an ssh login shell inherits nothing from
# pid 1. Without this, a tmux session that `ast attach` had to *create* would
# run the agent with no egress proxy and no credential handle, and the agent
# would fail in a way that looks like a broken key rather than a missing
# environment.
#
# What is copied is deliberately a list, not `env`: the proxy and CA variables
# Asterism exports, plus exactly the variables the preset said its secrets land
# in, named in `<workdir>/.asterism/agent.vars`. The values are opaque handles
# — worth nothing off this instance, and already on this disk inside pid 1's
# generated init — so writing them to a file adds no exposure. A raw key never
# reaches this guest at all, so there is none here to leak.
set -eu

WORK="${AST_AGENT_WORKDIR:-/work}"
VARS="$WORK/.asterism/agent.vars"
OUT=/etc/profile.d/10-asterism-agent.sh

names="HTTPS_PROXY HTTP_PROXY https_proxy http_proxy NO_PROXY no_proxy \
SSL_CERT_FILE CURL_CA_BUNDLE REQUESTS_CA_BUNDLE NODE_EXTRA_CA_CERTS"
if [ -f "$VARS" ]; then
  names="$names $(tr '\n' ' ' < "$VARS")"
fi

mkdir -p /etc/profile.d
tmp="$OUT.new"
: > "$tmp"
echo '# Generated by asterism-agent-env. Handles, never values.' >> "$tmp"
for name in $names; do
  case "$name" in
    ''|*[!A-Za-z0-9_]*) continue ;;
  esac
  value="$(printenv "$name" 2>/dev/null || true)"
  [ -n "$value" ] || continue
  # Single-quote the value and escape any quote inside it, so a handle that
  # happens to contain shell punctuation stays one word.
  escaped="$(printf '%s' "$value" | sed "s/'/'\\\\''/g")"
  printf "export %s='%s'\n" "$name" "$escaped" >> "$tmp"
done
chmod 0644 "$tmp"
mv "$tmp" "$OUT"
